---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
  {{- include "metadata" . | nindent 2 }}
spec:
  selector:
    matchLabels:
      app: {{ include "name" . }}
  replicas: {{ .Values.replicas }}
  progressDeadlineSeconds: 60
  strategy: {{ .Values.strategy | toYaml | nindent 4 }}
  template:
    metadata:
      {{- include "metadata" . | nindent 6 }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ include "name" . }}
        image: {{ .Values.image }}:{{ .Values.tag }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        ports:
        - name: {{ include "shortName" . }}
          containerPort: 80
          protocol: TCP
        livesnessProbe:
          tcpSocket:
            port: {{ include "shortName" . }}
        readnessProbe:
          httpGet:
            path: /
            port: {{ include "shortName" . }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        env:
        - name: APP_KEY
          value: '{{ .Values.speedtestTracker.apiKey }}'
        - name: APP_URL
          value: '{{ .Values.speedtestTracker.scheme }}://{{ .Values.speedtestTracker.domain }}'
        - name: ASSET_URL
          value: '{{ .Values.speedtestTracker.scheme }}://{{ .Values.speedtestTracker.domain }}'
        - name: SPEEDTEST_SCHEDULE
          value: '{{ .Values.speedtestTracker.cronSchedule }}'
        - name: SPEEDTEST_SERVERS
          value: '{{ .Values.speedtestTracker.servers }}'
        - name: PRUNE_RESULTS_OLDER_THAN
          value: '{{ .Values.speedtestTracker.pruneDays }}'
        - name: TZ
          value: '{{ .Values.speedtestTracker.timezone }}'
        - name: DB_CONNECTION
          value: 'sqlite'
        volumeMounts:
        - name: config
          mountPath: /config
          subPath: ./{{ .Values.speedtestTracker.configPath }}/{{ include "name" . }}
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: {{ .Values.speedtestTracker.pvc }}
...
