---
# -------------- Deployment -------------
{{- include "deployment.tpl" (list . "deployment.overlays") | nindent 0 -}}
{{- define "deployment.overlays" -}}
{{- $values := .Values.mongo | default dict -}}{{- $deployment := .Values.deployment | default (dict "image" dict) -}}
spec:
  template:
    spec:
      containers:
        - image: "{{ $deployment.image.repository }}:{{ $deployment.image.tag | default "latest" }}"
          ports:
            - name: "{{ include "svcName" . }}"
              containerPort: 27017
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
            - name: nfs
              mountPath: /data
              subPath: ./config/mongo
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: {{ $values.pvc | default "nfs" | quote }}
{{- end }}
---
# -------------- Service -------------
{{- include "service.tpl" (list . "service.overlays") | nindent 0 -}}
{{- define "service.overlays" -}}
spec:
  ports:
    - name: "{{ include "svcName" . }}"
      protocol: TCP
      port: 27017
      targetPort: "{{ include "svcName" . }}"
{{- end }}