---
- name: Install required packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - nano
    - python3
    - python3-pip
    - sshpass

- name: Install pipx (and upgrade pip)
  ansible.builtin.pip:
    name: pip
    executable: pip3
    state: latest
  with_items:
    - pip
    - pipx

- name: Install Ansible
  community.general.pipx:
    name: ansible
    install_deps: true
    state: latest