---
# Default values for System: MetalLB.

# --- | MetalLB configuration
metallb:
  addresses: [192.168.0.0/24]

# --- | Metadata values

# This is to override the chart name.
nameOverride: ''
# Specify extra annotations.
annotations: {}
# Specify extra labels.
labels: {}
...
