---
# --- | Default values for MetalLb
metallb:
  # List or comma-separated string of IP addresses used by the pool
  addresses: ""

# --- | Overriding 'template' chart values
metadata:
  # Additional component label
  labels:
    app.kubernetes.io/component: "load-balancer"
