---
apiVersion: v2
name: wg-easy
version: 0.1.0
type: application
description: |
  WG-Easy VPN (WireGuard) is a simple WireGuard VPN server with a web-based management interface.
sources:
  - https://github.com/wg-easy/wg-easy
  - https://www.wireguard.com/
appVersion: "latest"
icon: https://play-lh.googleusercontent.com/tixGgVipnsaKeGQzykJfgSEhUc_YYMSsr3gwBuPTpXb2F1BKPVzv5OxfCrpS8OAXXh8=w480-h960-rw
home: https://cosasdepuma.github.io/homelab/

maintainers:
  - name: Kike Fontan
    email: helm@kike.wtf
    url: https://github.com/cosasdepuma/
keywords:
  - cosasdepuma
  - homelab
  - wg-easy
  - wireguard
  - vpn
  - networking
...
