---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  {{- include "metadata" . | nindent 2 }}
spec:
  selector:
    app: {{ include "shortName" . }}
  ports:
  - name: {{ include "shortName" . }}-webui
    port: 51821
    protocol: TCP
    targetPort: {{ include "shortName" . }}-webui
  - name: {{ include "shortName" . }}-vpn
    port: 51820
    protocol: UDP
    targetPort: {{ include "shortName" . }}-vpn
...
