---
releases:

  # ==========================
  #   KIKEWTF
  # ==========================

  # ---- | DuckDNS
  - name: duckdns
    chart: ./helm/duckdns
    namespace: "kikewtf"
    labels: { env: "kikewtf" }
    values:
      - duckdns:
          subdomains: "{{ requiredEnv "DUCKDNS_SUBDOMAINS" }}"
          token: "{{ requiredEnv "DUCKDNS_TOKEN" }}"
