---
environments:
  system: {}
  kikewtf: {}
  hackres: {}
---
repositories:
- name: metallb
  url: https://metallb.github.io/metallb
- name: traefik
  url: https://traefik.github.io/charts

releases:

# --- | RELEASE :: KIKE.WTF | ---

# Storage: NFS
- name: nfs
  namespace: kikewtf
  chart: ./helm/nfs
  labels:
    environment: kikewtf
  values:
  - nfs:
      server: '{{ requiredEnv "NFS_SERVER" }}'
      path: '{{ requiredEnv "NFS_PATH" }}'
      capacity: '{{ requiredEnv "NFS_CAPACITY" }}'

# Bind9
- name: bind9
  namespace: kikewtf
  chart: ./helm/bind9
  labels:
    environment: kikewtf
  values:
  - bind9:
      banner: Kike DNS!
      hostIP: '{{ requiredEnv "HOST" }}'
      zones:
      - name: '{{ requiredEnv "DOMAIN" }}'
        records:
        - name: '*'
          type: A
          target: '{{ requiredEnv "HOST" }}'

# DuckDNS
- name: duckdns
  namespace: kikewtf
  chart: ./helm/duckdns
  labels:
    environment: kikewtf
  values:
  - duckdns:
      token: {{ requiredEnv "DUCKDNS_TOKEN" | quote }}
      subdomains: {{ requiredEnv "DUCKDNS_SUBDOMAINS" | quote }}

# OpenLDAP
- name: openldap
  namespace: kikewtf
  chart: ./helm/openldap
  labels:
    environment: kikewtf
  values:
  - openldap:
      route: HostSNI(`ldap.{{ requiredEnv "DOMAIN" }}`)
      organization: Kike WTF!
      domain: {{ requiredEnv "DOMAIN" | quote }}
      password:
        admin: {{ requiredEnv "ADMIN_PASSWORD" | quote }}

# WG-Easy
- name: wgeasy
  namespace: kikewtf
  chart: ./helm/wg-easy
  labels:
    environment: kikewtf
  values:
  - wgEasy:
      route: Host(`vpn.{{ requiredEnv "DOMAIN" }}`)
      hostIP: '{{ requiredEnv "DUCKDNS_SUBDOMAINS" | splitList "/" | first }}.duckdns.org'
      dns: '{{ requiredEnv "HOST" }}'
      lang: 'es'

# Speedtest Tracker
- name: speedtest
  namespace: kikewtf
  chart: ./helm/speedtest-tracker
  labels:
    environment: kikewtf
  values:
  - speedtestTracker:
      route: Host(`speed.{{ requiredEnv "DOMAIN" }}`)
      apiKey: '{{ requiredEnv "SPEEDTEST_APIKEY" }}'
      scheme: 'https'
      domain: 'speed.{{ requiredEnv "DOMAIN" }}'
      cronSchedule: '*/30 * * * *'
      servers: '8109,15111,35211,37211,40135,44255,50902,52295,56355,62958'
      timezone: '{{ requiredEnv "TZ" }}'

# Homepage
- name: homepage
  namespace: kikewtf
  chart: ./helm/homepage
  labels:
    environment: kikewtf
  values:
  - dns:
    - '{{ requiredEnv "HOST" }}'
  - homepage:
      route: Host(`home.{{ requiredEnv "DOMAIN" }}`)
      settings: |
        title: Kike! WTF?
        theme: dark
        color: slate
        statusStyle: dot
        hideVersion: true
        layout:
          Services:
            style: row
            columns: 4
          ServicesWidget:
            style: row
            columns: 4
            header: false
          Daemons:
            style : row
            columns: 3
          Hardware:
            style: column
          DNS:
            style: column
      services: |
        - Services:
          - Authelia:
              description: SSO provider
              icon: https://cdn.discordapp.com/icons/707844280412012608/731420b708a2bf5129dea9d421d3c6b4.webp
              href: https://auth.{{ requiredEnv "DOMAIN" }}
              siteMonitor: https://auth.{{ requiredEnv "DOMAIN" }}
        - ServicesWidget:
          - Speedtest Tracker:
              description: Internet performance tracking
              icon: https://speedtest-tracker.dev/img/speedtest-tracker-icon.png
              href: https://speed.{{ requiredEnv "DOMAIN" }}
              siteMonitor: https://speed.{{ requiredEnv "DOMAIN" }}
              widget:
                type: speedtest
                url: https://speed.{{ requiredEnv "DOMAIN" }}
                fields: ['upload','download']
          - WG-Easy:
              description: WireGuard VPN
              icon: https://play-lh.googleusercontent.com/tixGgVipnsaKeGQzykJfgSEhUc_YYMSsr3gwBuPTpXb2F1BKPVzv5OxfCrpS8OAXXh8=w480-h960-rw
              href: https://vpn.{{ requiredEnv "DOMAIN" }}
              siteMonitor: https://vpn.{{ requiredEnv "DOMAIN" }}
              widget:
                type: wgeasy
                password: 'nopassword'
                url: https://vpn.{{ requiredEnv "DOMAIN" }}
                fields: ['connected','enabled']
        - Daemons:
          - DuckDNS:
              description: DynDNS
              icon: https://www.duckdns.org/img/ducky_icon_small.png
              href: http://{{ requiredEnv "DUCKDNS_SUBDOMAINS" | splitList "/" | first }}.duckdns.org
              ping: {{ requiredEnv "DUCKDNS_SUBDOMAINS" | splitList "/" | first }}.duckdns.org
            
      bookmarks: |
        - Hardware:
          - Router:
            - href: http://192.168.1.1/
              icon: https://upload.wikimedia.org/wikipedia/commons/1/1d/Digi_Logo.png
              description: H3600 V9
        - DNS:
          - Cloudflare:
            - href: https://dash.cloudflare.com/
              icon: https://upload.wikimedia.org/wikipedia/commons/9/94/Cloudflare_Logo.png
              description: Network services and cloud provider.
          - DuckDNS:
            - href: https://www.duckdns.org/
              icon: https://www.duckdns.org/img/ducky_icon_small.png
              description: Free and reliable DynDNS provider.
      widgets: |
        - resources:
            cpu: true
            memory: true
            disk: /
        - datetime:
            format:
              dateStyle: short
              timeStyle: short

# --- | RELEASE :: HACKR.ES | ---

# Storage: NFS
- name: nfs
  namespace: hackres
  chart: ./helm/nfs
  labels:
    environment: hackres
  values:
  - storageNFS:
      server: '{{ requiredEnv "NFS_SERVER" }}'
      path: '{{ requiredEnv "NFS_PATH" }}'
      capacity: '{{ requiredEnv "NFS_CAPACITY" }}'

# DuckDNS
- name: duckdns
  namespace: hackres
  chart: ./helm/duckdns
  labels:
    environment: hackres
  values:
  - duckdns:
      token: '{{ requiredEnv "DUCKDNS_TOKEN" }}'
      subdomains: '{{ requiredEnv "DUCKDNS_SUBDOMAINS" }}'

# --- | KUBE SYSTEM | ---

# MetalLB
- name: metallb-base
  namespace: kube-system
  chart: metallb/metallb
  wait: true
  labels:
    environment: system
- name: metallb
  needs: [metallb-base]
  namespace: kube-system
  chart: ./helm/metallb
  labels:
    environment: system
  values:
  - metallb:
      addresses: ['{{ requiredEnv "METALLB_IPRANGE" }}']

# Traefik
- name: traefik
  needs: [metallb]
  namespace: kube-system
  chart: traefik/traefik
  wait: true
  labels:
    environment: system
  values:
  - env:
    - name: '{{ requiredEnv "ACME_TOKEN_NAME" }}'
      value: '{{ requiredEnv "ACME_TOKEN_VALUE" }}'
  - ports:
      dns-tcp:
        protocol: TCP
        port: 8053
        exposedPort: 53
        expose:
          default: true
      dns-udp:
        protocol: UDP
        port: 8053
        exposedPort: 53
        expose:
          default: true
      web:
        protocol: TCP
        port: 8080
        exposedPort: 80
        expose:
          default: true
      websecure:
        protocol: TCP
        port: 8443
        exposedPort: 443
        expose:
          default: true
      traefik:
        protocol: TCP
        port: 9000
        exposedPort: 9000
        expose:
          default: true
      wireguard:
        protocol: UDP
        port: 51820
        exposedPort: 51820
        expose:
          default: true
  - additionalArguments:
    - '--api=true'
    - '--api.dashboard=true'
    - '--api.disabledashboardad=true'
    - '--api.insecure=true'
    - "--certificatesresolvers.letsencrypt.acme.email={{ requiredEnv "ACME_EMAIL" }}"
    - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
    - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider={{ requiredEnv "ACME_PROVIDER" }}"
    - "--certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=0"
    - "--certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
    - '--entrypoints.web=true'
    - '--entrypoints.web.address=:8080/tcp'
    - '--entrypoints.web.asdefault=true'
    - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
    - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
    - '--entrypoints.websecure=true'
    - '--entrypoints.websecure.address=:8443/tcp'
    - '--entrypoints.websecure.http.tls=true'
    - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
    {{ range $index,$domain := (requiredEnv "ACME_DOMAINS" | split ",") }}
    - "--entrypoints.websecure.http.tls.domains[{{$index}}].main={{ $domain }}"
    - "--entrypoints.websecure.http.tls.domains[{{$index}}].sans=*.{{ $domain }}"
    {{ end }}
    - '--entrypoints.ldap=:8369/tcp'
    - '--entrypoints.ldap.address=:8369/tcp'
    - '--entrypoints.dns-tcp=true'
    - '--entrypoints.dns-tcp.address=:8053/tcp'
    - '--entrypoints.dns-udp=true'
    - '--entrypoints.dns-udp.address=:8053/udp'
    - '--entrypoints.traefik=true'
    - '--entrypoints.traefik.address=:9000/tcp'
    - '--entrypoints.metrics=true'
    - '--entrypoints.metrics.address=:9100/tcp'
    - '--entrypoints.wireguard=true'
    - '--entrypoints.wireguard.address=:51820/udp'
    - '--global.checknewversion=true'
    - '--global.sendanonymoususage=false'
    - '--log=true'
    - '--log.format=json'
    - '--log.level=DEBUG'
    - '--metrics.prometheus=true'
    - '--metrics.prometheus.entrypoint=metrics'
    - '--ping=true'
    - '--providers.kubernetescrd=true'
    - '--providers.kubernetescrd.allowemptyservices=true'
    - '--providers.kubernetesingress=true'
    - '--providers.kubernetesingress.allowemptyservices=true'
...
