---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name:  {{ include "name" . }}
  {{- include "metadata" . | nindent 2 }}
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: {{ .Values.jellyfin.route }}
    services:
    - name: {{ include "name" . }}
      port: {{ include "shortName" . }}
...