---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  {{- include "metadata" . | nindent 2 }}
spec:
  selector:
    app: {{ include "name" . }}
  ports:
  - name: {{ include "shortName" . }}
    port: 8096
    protocol: TCP
    targetPort: {{ include "shortName" . }}-webui
...