apiVersion: v2
name: bind9
version: 0.1.0
type: application
description: |
  Bind9 is a complete implementation of the DNS protocol.
sources:
  - https://www.isc.org/bind/
appVersion: "latest"
icon: https://jellyfin.org/images/logo.svg
home: https://cosasdepuma.github.io/homelab/

maintainers:
  - name: Kike Fontan
    email: helm@kike.wtf
    url: https://github.com/cosasdepuma/
keywords:
  - cosasdepuma
  - homelab
  - bind9
  - dns
  - networking

dependencies:
  - name: template
    version: 1.0.0
    repository: file://../_template
