---
apiVersion: "v2"
name: "homelab"
version: "1.0.0"
type: "application"
description: |-
  This Chart contains the configuration to automatically deploy my homelab configuration almost in its entirety.
sources:
  - "https://github.com/cosasdepuma/homelab"
appVersion: "latest"
home: "https://cosasdepuma.github.io/HomeLab/"

maintainers:
  - name: "Kike Fontan"
    email: "helm@kike.wtf"
    url: "https://github.com/cosasdepuma/"
keywords:
  - "cosasdepuma"
  - "homelab"
  - "aoi"
  - "all-in-one"
  - "self-hosted"

dependencies:
  - name: "bind9"
    version: "1.0.0"
    repository: "file://../bind9"
    condition: "bind9.enabled"
  - name: "metallb"
    version: "1.0.0"
    repository: "file://../metallb"
    condition: "metallb.enabled"
  - name: "nfs"
    version: "1.0.0"
    repository: "file://../nfs"
    condition: "nfs.enabled"
  - name: "traefik"
    version: "1.0.0"
    repository: "file://../traefik"
    condition: "traefik.enabled"
...
