---
api:
  dashboard: true
  insecure: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: pumita-homelab@example.com
      storage: /etc/traefik/certificates
      httpChallenge:
        entryPoint: http

entrypoints:
  http:
    address: :80
      
  https:
    address: :443
    http:
      tls:
        options: strong
        certResolver: letsencrypt

global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  format: common
  level: INFO

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    watch: true
  
  file:
    directory: /etc/traefik
    watch: true