---
# --- | Default values for DuckDNS.
duckdns:
  # Comma-separated list of DuckDNS subdomains (without .duckdns.org)
  subdomains: ""
  # DuckDNS token (https://www.duckdns.org/)
  token: ""
  # DuckDNS update IP (ipv4, ipv6, both)
  updateIP: "ipv4"

# --- | Overriding 'template' chart values
deployment:
  # Image repository
  image:
    repository: "lscr.io/linuxserver/duckdns"

metadata:
  # Additional component label
  labels:
    app.kubernetes.io/component: "dns"
