---
# -------------- ConfigMap -------------
{{- include "configmap.tpl" (list . "configmap.overlays") | nindent 0 -}}
{{- define "configmap.overlays" -}}
{{- $values := .Values.phpldapadmin | default dict -}}
metadata:
  name: "{{ include "name" . }}"
data:
  PHPLDAPADMIN_LDAP_HOSTS: "{{ $values.ldapHost | default "127.0.0.1" }}"
  PHPLDAPADMIN_HTTPS: "false"
{{- end }}
---
# -------------- Deployment -------------
{{- include "deployment.tpl" (list . "deployment.overlays") | nindent 0 -}}
{{- define "checksums" -}}
metadata:
  annotations:
    checksum/configmap: {{ include "configmap.tpl" (list . "configmap.overlays") | sha256sum | quote }}
{{- end -}}
{{- define "deployment.overlays" -}}
{{- $values := .Values.phpldapadmin | default dict -}}
{{- include "checksums" . | nindent 0 }}
spec:
  template:
    {{- include "checksums" . | nindent 4 }}
    spec:
      {{- if $values.dns }}
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          {{- $values.dns | toYaml | nindent 10 }}
      {{- end }}
      containers:
        - name: {{ include "name" . | quote }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default "latest" }}"
          envFrom:
            - configMapRef:
                name: {{ include "name" . | quote }}
          ports:
            - name: {{ include "svcName" . | quote }}
              containerPort: 80
              protocol: TCP
{{- end }}
---
# -------------- Service -------------
{{- include "service.tpl" (list . "service.overlays") | nindent 0 -}}
{{- define "service.overlays" -}}
spec:
  ports:
    - name: {{ include "svcName" . | quote }}
      protocol: TCP
      port: 80
      targetPort: {{ include "svcName" . | quote }}
{{- end }}
---
# -------------- IngressRoute -------------
{{- include "ingressroute.tpl" (list . "ingressroute.overlays") | nindent 0 -}}
{{- define "ingressroute.overlays" -}}
{{- $values := .Values.phpldapadmin | default dict -}}
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`{{ $values.domain | default "*" }}`)"
      services:
        - name: {{ include "name" . | quote }}
          port: {{ include "svcName" . | quote }}
{{- end }}
