---
version: '3.8'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      DOMAIN: "https://${VAULTWARDEN_DOMAIN}"
    volumes:
      - ${VAULTWARDEN_CONFIG:-/data/config/vaultwarden}:/data:rw
    hostname: vault
    network_mode: bridge
    ports:
      - ${VAULTWARDEN_PORT:-80}:80
    restart: unless-stopped