apiVersion: v2
name: jellyfin
version: 0.1.0
type: application
description: |
  Jellyfin is a media system to control, manage and streaming your media.
sources:
  - https://jellyfin.org/
appVersion: "latest"
icon: https://jellyfin.org/images/logo.svg
home: https://cosasdepuma.github.io/homelab/

maintainers:
  - name: Kike Fontan
    email: helm@kike.wtf
    url: https://github.com/cosasdepuma/
keywords:
  - cosasdepuma
  - homelab
  - jellyfin
  - media
  - streaming