{{- $values := .Values.nfs | default dict -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "name" . | quote }}
  labels:
    type: nfs
    {{- include "labels" . | nindent 4 }}
    {{- with $values.labels | default dict }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "annotations" . | nindent 4 }}
    {{- with $values.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  {{- if $values.capacity }}
  capacity:
    storage: {{ $values.capacity | quote }}
  {{- end }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: {{ $values.path | default "/" | quote }}
    {{- if $values.server }}
    server: {{ $values.server | quote }}
    {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "name" . | quote}}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- with $values.labels | default dict }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "annotations" . | nindent 4 }}
    {{- with $values.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      {{- if $values.capacity }}
      storage: {{ $values.capacity | quote }}
      {{- end }}
  selector:
    matchLabels:
      type: nfs
...