---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "name" . }}
  {{- include "metadata" . | nindent 2 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nfs.capacity }}
  selector:
    matchLabels:
      type: nfs
      environment: {{ .Release.Namespace }}
...
