---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Namespace }}-{{ include "name" . }}
  labels:
    type: nfs
    environment: {{ .Release.Namespace }}
    {{- include "labels" . | nindent 4 }}
  annotations:
    {{- include "annotations" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.nfs.capacity }}
  volumeMode: Filesystem
  #storageClassName: slow  # FIXME: Check if storageClassName is needed
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: {{ .Values.nfs.path }}
    server: {{ .Values.nfs.server }}
...