---
# === Homer configuration ===

# -- | Main
title: "HomeLab"
subtitle: "Pumita"

header: true
footer: "<p>Maybe wars aren't meant to be won, maybe they're meant to be continuous <span class=\"has-text-danger\">🤖</span></p>"

# -- | Theme
theme: "default"
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#282a36"
    card-background: "#fafafa"
    text: "#f8f8f2"
    text-header: "#f8f8f2"
    text-title: "#303030"
    text-subtitle: "#424242"
    link: "#3273dc"
    link-hover: "#363636"
    card-shadow: "rgba(0, 0, 0, 0.1)"
  dark:
    highlight-primary: "transparent"
    highlight-secondary: "#8466AE"
    highlight-hover: "#44475a"
    background: "#282a36"
    card-background: "#44475a"
    text: "#f8f8f2"
    text-header: "#f8f8f2"
    text-title: "#f8f8f2"
    text-subtitle: "#8be9fd"
    link: "#50fa7b"
    link-hover: "#50fa7b"
    card-shadow: "rgba(0, 0, 0, 0.4)"

# -- | Navbar
links:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/cosasdepuma/"
    target: "_blank"
  - name: "kike.wtf"
    icon: "fas fa-home"
    url: "https://www.kike.wtf/"
    target: "_blank"

# -- | Services
defaults:
  layout: "rows"
  colorTheme: "dark"

colums: 3
connectivityCheck: true

services:
  - name: "Management"
    icon: "fas fa-server"
    items:
      - name: "Metaverse"
        logo: "assets/icons/proxmox.png"
        subtitle: "Virtual Machines Management"
        tag: "os"
        keywords: "virtualization, hypervisor, kvm, lxc, openvz, proxmox, pve"
        url: "https://192.168.1.200:8006"
        target: "_blank"

      - name: "Whales"
        logo: "assets/icons/portainer.png"
        subtitle: "Containers Management"
        tag: "vm"
        keywords: "virtualization, containers, docker, portainer, kubernetes, k8s, compose, stack"
        url: "https://192.168.1.210:9443"
        target: "_blank"

      - name: "Signal"
        logo: "assets/icons/semaphore.png"
        subtitle: "Ansible Management"
        tag: "container"
        keywords: "semaphore, ansible, tower, playbooks, tasks, automation, vms"
        url: "http://192.168.1.210:3000"
        target: "_blank"

  - name: "Productivity"
    icon: "fas fa-coffee"
    items:
      - name: "Workbench"
        logo: "assets/icons/vscode.png"
        subtitle: "Visual Studio Code"
        tag: "container"
        keywords: "code, development, developer, vscode, visual studio code, editor, ide, integrated development environment"
        url: "http://192.168.1.210:8443"
        target: "_blank"

  - name: "Media"
    icon: "fas fa-photo-video"
    items:
      - name: "Jellyfish"
        logo: "assets/icons/jellyfin.png"
        subtitle: "Stream Media Solution"
        tag: "container"
        keywords: "movies, tv, series, music, jellyfin, plex, emby, kodi, media, stream, comics, ebooks"
        url: "http://192.168.1.210:8096"
        target: "_blank"

      - name: "Submarine"
        logo: "assets/icons/sonarr.png"
        subtitle: "TV Shows Management"
        tag: "container"
        keywords: "tv, series, anime, shows, sonarr, transmission, qbittorrent, rss"
        url: "http://192.168.1.210:8989"
        target: "_blank"

      - name: "Aladin"
        logo: "assets/icons/bazarr.png"
        subtitle: "Subtitles Manager"
        tag: "container"
        keywords: "tv, series, anime, shows, sonarr, radarr, rss, subtitles, bazarr"
        url: "http://192.168.1.210:6767"
        target: "_blank"
  
  - name: "Downloads"
    icon: "fas fa-download"
    items:
      - name: "Qubit"
        logo: "assets/icons/qbittorrent.png"
        subtitle: "Torrent Downloader"
        tag: "container"
        keywords: "torrent, download, magnet, qbittorrent, rss"
        url: "http://192.168.1.210:8080"
        target: "_blank"

      - name: "Taiga"
        logo: "assets/icons/prowlarr.png"
        subtitle: "Indexer Manager"
        tag: "container"
        keywords: "indexer, torrent, download, magnet, radarr, sonarr, lidarr, prowlarr, jackett, rss"
        url: "http://192.168.1.210:9696"
        target: "_blank"