---
version: '2'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      DOMAIN: "https://${VAULTWARDEN_DOMAIN}"
    volumes:
      - ${VAULTWARDEN_CONFIG:-/data/config/vaultwarden}:/data
    hostname: vault
    ports:
      - ${VAULTWARDEN_PORT:-80}:80
    restart: unless-stopped