---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
  {{- include "metadata" . | nindent 2 }}
spec:
  selector:
    matchLabels:
      app: {{ include "name" . }}
  replicas: {{ .Values.replicas }}
  progressDeadlineSeconds: 60
  strategy: {{ .Values.strategy | toYaml | nindent 4 }}
  template:
    metadata:
      {{- include "metadata" . | nindent 6 }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ include "name" . }}
          image: {{ .Values.image }}:{{ .Values.tag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "name" . }}-token
                  key: token
            - name: SUBDOMAINS
              value: {{ .Values.duckdns.subdomains }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
...