---
# -------------- ConfigMap -------------
{{- include "configmap.tpl" (list . "configmap.overlays") | nindent 0 -}}
{{- define "configmap.overlays" -}}
data:
  SUBDOMAINS: {{ .Values.duckdns.subdomains | quote }}
  UPDATE_IP: {{ .Values.duckdns.updateIP | default "both" | quote }}
{{- end }}
---
# -------------- Secret -------------
{{- include "secret.tpl" (list . "secret.overlays") | nindent 0 -}}
{{- define "secret.overlays" -}}
data:
  TOKEN: {{ .Values.duckdns.token | b64enc | quote }}
{{- end }}
---
# -------------- Deployment -------------
{{- include "deployment.tpl" (list . "deployment.overlays") | nindent 0 -}}
{{- define "deployment.overlays" -}}
metadata:
  annotations:
    checksum/configmap: {{- include "secret.tpl" (list . "configmap.overlays") | sha256sum | quote -}}
    checksum/secret: {{- include "secret.tpl" (list . "secret.overlays") | sha256sum | quote -}}
spec:
  template:
    spec:
      containers:
        - image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default "latest" }}"
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
      volumes:
        - name: env-config
          configmap:
            name: {{ include "name" . | quote }}
        - name: env-secret
          secret:
            secretName: {{ include "name" . | quote }}
{{- end }}
