---
apiVersion: v2
name: komga
version: 0.1.0
type: application
description: |
  Komga is a media server for your comics, mangas, BDs, magazines and eBooks
sources:
  - https://komga.org/
appVersion: "latest"
icon: https://komga.org/img/logo.svg
home: https://cosasdepuma.github.io/homelab/

maintainers:
  - name: Kike Fontan
    email: helm@kike.wtf
    url: https://github.com/cosasdepuma/
keywords:
  - cosasdepuma
  - homelab
  - komga
  - reader
  - ebook

dependencies:
  - name: template
    version: 1.0.0
    repository: file://../_template
