---
apiVersion: v2
name: speedtest-tracker
version: 0.1.0
type: application
description: |
  Speedtest Tracker is a self-hosted internet performance tracking application that runs speedtest checks against Ookla's Speedtest service.
sources:
  - https://speedtest-tracker.dev/
appVersion: "latest"
icon: https://speedtest-tracker.dev/img/speedtest-tracker-icon.png
home: https://cosasdepuma.github.io/homelab/

maintainers:
  - name: Kike Fontan
    email: helm@kike.wtf
    url: https://github.com/cosasdepuma/
keywords:
  - cosasdepuma
  - homelab
  - speedtest-tracker
  - speedtest
  - internet
  - networking
