---
# Default values for Speedtest Tracker.

# --- | Speedtest Tracker configuration
speedtestTracker:
  route: Host(`*`)
  # Speedtest Tracker API key (https://speedtest-tracker.dev/)
  apiKey: ""
  # URL scheme
  scheme: "http"
  # Domain name
  domain: "example.com"
  # Prune data older than this many days
  pruneDays: 15
  # Cron schedule for running the tests
  cronSchedule: "0 * * * *"
  # Comma-separated server IDs to randomly test against (https://c.speedtest.net/speedtest-servers-static.php)
  servers: ""
  # Timezone to use for cron schedule
  timezone: "UTC"
  # The PVC used for the deployment.
  pvc: storage-nfs
  # Config path inside PVC
  configPath: /config

# --- | Metadata values

# This is to override the chart name.
nameOverride: ""
# Specify extra annotations.
annotations: {}
# Specify extra labels.
labels: {}

# --- | Deployment values

# The image to deploy
image: "lscr.io/linuxserver/speedtest-tracker"
# The version of the image to deploy
tag: "latest"
# Specifies the image pull policy.
pullPolicy: IfNotPresent
# The number of replicas to deploy.
replicas: 1
# The strategy to use for the deployment.
# More information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
# The resources to allocate to the container.
resources:
  requests:
    memory: 128Mi
    cpu: 50m
  limits:
    memory: 512Mi
    cpu: 150m
