---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ include "name" . }}
  {{- include "metadata" . | nindent 2 }}
spec:
  ipAddressPoolSelectors:
  - matchLabels:
      app: {{ include "name" . }}
...