{{- $values := .Values.metallb | default dict -}}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ include "name" . | quote}}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- with $values.labels | default dict }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "annotations" . | nindent 4 }}
    {{- with $values.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  {{- if $values.addresses }}
  addresses:
    {{- $addresses := $values.addresses | toYaml -}}
    {{- if kindIs "string" $values.addresses -}}{{- $addresses = split "," $values.addresses | include "map2slice" -}}{{- end -}}
    {{- $addresses | nindent 4 }}
  {{- end }}
  avoidBuggyIPs: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ include "name" . | quote}}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- with $values.labels | default dict }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "annotations" . | nindent 4 }}
    {{- with $values.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  ipAddressPoolSelectors:
  - matchLabels:
      app: {{ include "name" . | quote }}
...
