---
# -------------- IPAddressPool -------------
{{- include "ipaddresspool.tpl" (list . "ipaddresspool.overlays") | nindent 0 -}}
{{- define "ipaddresspool.overlays" -}}
spec:
  addresses:
    {{- with .Values.addresses }}
    {{ . | toYaml | nindent 4 }}
    {{- end }}
{{- end }}
---
# -------------- L2Advertisement -------------
{{- include "l2advertisement.base.tpl" . | nindent 0 }}
...
