---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ include "name" . }}
  {{- include "metadata" . | nindent 2 }}
spec:
  addresses: {{ .Values.metallb.addresses }}
  avoidBuggyIPs: true
...