---
version: '3.8'

services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    environment:
      EDIT_MODE_PASSWORD: ${HOMARR_PASSWORD:-homarr}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ${HOMARR_CONFIG:-/data/config/homarr}:/app/data/configs
      - ${HOMARR_ASSETS:-../../icons}:/app/public/icons
    hostname: lobster
    network_mode: bridge
    ports:
      - ${HOMARR_PORT:-7575}:7575/tcp
    restart: unless-stopped