---
version: '3.8'
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    environment:
      PUID: ${NGINXPM_UID:-1000}
      PGID: ${NGINXPM_GID:-1000}
      DISABLE_IPV6: ${NGINXPM_NOIPV6:-true}
      X_FRAME_OPTIONS: ${NGINXPM_NOIPV6:-deny}
    volumes:
      - ${NGINXPM_CONFIG:-/data/config/nginx-pm}:/data:rw
      - ${CERTIFICATES:-/data/certificates}:/etc/letsencrypt:rw
    hostname: accreditor
    network_mode: bridge
    ports:
      - 80:80/tcp
      - 81:81/tcp
      - 443:443/tcp
    healthcheck:
      test: [ "CMD", "/bin/check-health" ]
      interval: 10s
      timeout: 3s
    restart: unless-stopped

networks:
  default:
    name: proxy
    external: true