---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}
  {{- include "metadata" . | nindent 2 }}
data:
    
    schema.ldif: |
      dn: ou=users,{{ `{{ LDAP_BASE_DN }}` }}
      objectClass: organizationalUnit
      ou: users

      dn: ou=groups,{{ `{{ LDAP_BASE_DN }}` }}
      objectClass: organizationalUnit
      ou: groups

      dn: cn=admins,ou=groups,{{ `{{ LDAP_BASE_DN }}` }}
      cn: admins
      objectclass: groupOfUniqueNames
      objectclass: top
      uniquemember: cn=admins,ou=groups,{{ `{{ LDAP_BASE_DN }}` }}

      dn: cn=users,ou=groups,{{ `{{ LDAP_BASE_DN }}` }}
      objectClass: posixGroup
      cn: users
      gidNumber: 5000
...