---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name:  {{ include "name" . }}
  {{- include "metadata" . | nindent 2 }}
spec:
  entryPoints:
  - ldap
  routes:
  - kind: Rule
    match: {{ .Values.openldap.route }}
    services:
    - name: {{ include "shortName" . }}
      port: {{ include "shortName" . }}
...