---
# -------------- ConfigMap -------------
{{- include "configmap.tpl" (list . "configmap-env.overlays") | nindent 0 -}}
{{- define "configmap-env.overlays" -}}
{{- $values := .Values.openldap | default dict -}}
metadata:
  name: "{{ include "name" . }}-env"
data:
  BITNAMI_DEBUG: "true"
  LDAP_ROOT: {{ $values.basedn | default "dc=example,dc=com" | quote }}
  LDAP_SKIP_DEFAULT_TREE: "yes"
  LDAP_ALLOW_ANON_BINDING: "no"
  LDAP_ADMIN_USERNAME: {{ ($values.admin | default dict).user | default "admin" | quote }}
{{- end }}
---
{{- include "configmap.tpl" (list . "configmap-ldif.overlays") | nindent 0 -}}
{{- define "configmap-ldif.overlays" -}}
{{- $values := .Values.openldap | default dict -}}
metadata:
  name: "{{ include "name" . }}-ldif"
data:
  {{- range $key, $value := $values.ldifs | default dict }}
  {{ $key }}: |-
    {{ $value | nindent 4 }}
  {{- end }}
{{- end }}
---
# -------------- Secret -------------
{{- include "secret.tpl" (list . "secret.overlays") | nindent 0 -}}
{{- define "secret.overlays" -}}
{{- $values := .Values.openldap | default dict -}}
data:
  LDAP_ADMIN_PASSWORD: {{ ($values.admin | default dict).pass | default "password" | b64enc | quote }}
{{- end }}
---
# -------------- Deployment -------------
{{- include "deployment.tpl" (list . "deployment.overlays") | nindent 0 -}}
{{- define "checksums" -}}
metadata:
  annotations:
    checksum/configmap-env: {{ include "configmap.tpl" (list . "configmap-env.overlays") | sha256sum | quote }}
    checksum/configmap-ldif: {{ include "configmap.tpl" (list . "configmap-ldif.overlays") | sha256sum | quote }}
    checksum/secret: {{ include "secret.tpl" (list . "secret.overlays") | sha256sum | quote }}
{{- end }}
{{- define "deployment.overlays" -}}
{{- include "checksums" . | nindent 0 }}
spec:
  template:
    {{- include "checksums" . | nindent 4 }}
    spec:
      containers:
        - image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default "latest" }}"
          ports:
            - name: {{ include "svcName" . | quote }}
              containerPort: 1389
              protocol: TCP
          envFrom:
            - configMapRef:
                name: "{{ include "name" . }}-env"
            - secretRef:
                name: "{{ include "name" . }}"
          volumeMounts:
            - name: ldif
              mountPath: /ldifs
              readOnly: true
      volumes:
        - name: ldif
          configMap:
            name: "{{ include "name" . }}-ldif"
{{- end }}
---
# -------------- Service -------------
{{- include "service.tpl" (list . "service.overlays") | nindent 0 -}}
{{- define "service.overlays" -}}
spec:
  ports:
    - name: {{ include "svcName" . | quote }}
      protocol: TCP
      port: 1389
      targetPort: {{ include "svcName" . | quote }}
{{- end }}
# -------------- IngressRoute -------------
---
{{- include "ingressroutetcp.tpl" (list . "ingressroutetcp.overlays") | nindent 0 -}}
{{- define "ingressroutetcp.overlays" -}}
{{- $values := .Values.openldap | default dict -}}
spec:
  entryPoints:
    - ldap
  routes:
    - match: "HostSNI(`*`)"
      services:
        - name: {{ include "name" . | quote }}
          port: {{ include "svcName" . | quote }}
{{- end }}
