---
- hosts: proxmox
  remote_user: root
  vars:
    os_flavour: bookworm
    vlan_enabled: false
  roles:
    - proxmox
    - default
- hosts: portainer
  remote_user: root
  vars:
    share: /share
    domain: lab.kike.wtf
    password: homelab
  roles:
    - default
    - containers