---
- hosts: all
  become: true
  handlers:
    - name: sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
  roles:
    - default

- hosts: proxmox
  become: true
  vars:
    os_flavour: bookworm
    vlan_enabled: false
  roles:
    - proxmox

- hosts: portainer
  become: true
  vars:
    share: /share
    domain: lab.kike.wtf
    password: homelab
  roles:
    - containers

#- hosts: ansible
#  become: true
#  roles:
#    - ansible