---
http:
  middlewares:
    default:
      chain:
        middlewares:
          - jokes@file
          - security@file
          - performance@file

    https:
      chain:
        middlewares:
          - https-redirect@file
          - hsts@file

    performance:
      chain:
        middlewares:
          - buffering@file
          - compression@file

    security:
      chain:
        middlewares:
          - https@file
          - security-headers@file

    strong-security:
      chain:
        middlewares:
          security@file
          extra-security-headers@file