---
http:
  middlewares:
    buffering:
      buffering:
        maxRequestBodyBytes: 2000000 # 2MB

    compression:
      compress:
        minResponseBodyBytes: 1024
        excludedContentTypes:
          - text/event-stream