---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}
  {{- include "metadata" . | nindent 2 }}
data:
    named.conf: |
        acl internal {
            10.0.0.0/8;
            127.0.0.0/8;
            172.16.0.0/12;
            192.168.0.0/16;
        };

        options {
            directory "/var/cache/bind";
            dnssec-validation auto;
            auth-nxdomain no;                         # conform to RFC1035
            listen-on { any; };
            listen-on-v6 { any; };
            recursion yes;
            allow-recursion { internal; };
            allow-query { internal; };
            allow-query-cache { internal; };
            allow-transfer { none; };
            empty-zones-enable no;
            querylog yes;
            version "{{ .Values.bind9.banner }}";
            forward only;
            forwarders {
        {{- range .Values.bind9.forwarders }}
                {{ . }};
        {{- end }}
            };
        };

        // External zones

        zone "."  {
            type hint;
            file "/usr/share/dns/root.hints";
        };
        zone "localhost" {
            type master;
            file "/etc/bind/db.local";
        };
        zone "127.in-addr.arpa" {
            type master;
            file "/etc/bind/db.127";
        };
        zone "0.in-addr.arpa" {
            type master;
            file "/etc/bind/db.0";
        };
        zone "255.in-addr.arpa" {
            type master;
            file "/etc/bind/db.255";
        };

        // Custom zones


        {{- if .Values.bind9.zones }}
        {{- range .Values.bind9.zones }}
        zone "{{ .name }}" IN {
            type master;
            file "/etc/bind/zones/{{ .name }}";
            allow-update { none; };
        };
        {{- end }}
        {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-zones
  {{- include "metadata" . | nindent 2 }}
data:
{{- range $zone := .Values.bind9.zones }}
    {{ $zone.name }}: |
        $TTL 604800
        $ORIGIN {{ $zone.name }}.
        @ IN SOA ns.{{ $zone.name }}. root.{{ $zone.name }}. (
            2022072651  ; serial
            3600        ; refresh
            1800        ; retry
            2419200     ; expire
            604800 )    ; negative cache TTL
        ;
        @ IN NS ns.{{ .name }}.
        @ IN A {{ $.Values.bind9.hostIP }}
        ns IN A {{ $.Values.bind9.hostIP }}
        ;
        {{- range $zone.records }}
        {{ .name }} IN {{ .type }} {{ .target }}
        {{- end }}
{{- end }}
...