---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
  {{- include "metadata" . | nindent 2 }}
spec:
  selector:
    matchLabels:
      app: {{ include "name" . }}
  replicas: {{ .Values.replicas }}
  progressDeadlineSeconds: 60
  strategy: {{ .Values.strategy | toYaml | nindent 4 }}
  template:
    metadata:
      {{- include "metadata" . | nindent 6 }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ include "name" . }}
        image: {{ .Values.image }}:{{ .Values.tag }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        ports:
        - name: {{ include "shortName" . }}-tcp
          containerPort: 53
          protocol: TCP
        - name: {{ include "shortName" . }}-udp
          containerPort: 53
          protocol: UDP
        livesnessProbe:
          tcpSocket:
            port: {{ include "shortName" . }}-tcp
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        volumeMounts:
        - name: config
          mountPath: /etc/bind/named.conf
          subPath: named.conf
          readOnly: true
        - name: zones
          mountPath: /etc/bind/zones
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "name" . }}
        - name: zones
          configMap:
            name: {{ include "name" . }}-zones
...
