---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  {{- include "metadata" . | nindent 2 }}
spec:
  selector:
    app: {{ include "name" . }}
  ports:
  - name: {{ include "shortName" . }}-tcp
    port: 53
    protocol: TCP
    targetPort: {{ include "shortName" . }}-tcp
  - name: {{ include "shortName" . }}-udp
    port: 53
    protocol: UDP
    targetPort: {{ include "shortName" . }}-udp
...