---
apiVersion: v2
name: openldap
version: 0.1.0
type: application
description: |
  OpenLDAP is a free, open-source implementation of the Lightweight Directory Access Protocol (LDAP) developed by the OpenLDAP Project.
sources:
  - https://www.openldap.org
appVersion: "latest"
icon: https://cdn.discordapp.com/icons/707844280412012608/731420b708a2bf5129dea9d421d3c6b4.webp
home: https://cosasdepuma.github.io/homelab/

maintainers:
  - name: Kike Fontan
    email: helm@kike.wtf
    url: https://github.com/cosasdepuma/
keywords:
  - cosasdepuma
  - homelab
  - authelia
  - sso
  - identity
