---
name: "Helm repository"
on:
  push:
    branches: ["main"]
  workflow_dispatch:
    branches: ["main"]

jobs:
  main:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Clone the main branch"
        uses: "actions/checkout@v4"
        with:
          ref: "main"
      - name: "Save the charts into an artifact"
        uses: "actions/upload-artifact@v4"
        with:
          name: "helm-charts"
          path: "./helm/"

  gh-pages:
    needs: ["main"]
    runs-on: "ubuntu-latest"
    steps:
      - name: "Clone the gh-pages branch"
        uses: "actions/checkout@v4"
        with:
          ref: "gh-pages"
      - name: "Download the artifacts"
        uses: "actions/download-artifact@v4"
        with:
          name: "helm-charts"
          path: "/tmp/charts"
      - name: "Install Helm CLI"
        uses: "azure/setup-helm@v4"
        with:
          version: "latest"
      - name: "Package the charts"
        run: |
          find /tmp/charts -name "Chart.yaml" -execdir helm dependency update \;
          helm package /tmp/charts/* -d ./charts
          helm repo index . --url "https://${{ github.actor }}.github.io/$(basename ${{ github.repository }})"
      - name: "Commit the changes"
        run: |
          git add --all
          git config --global user.name "Continuous Integration (GitHub Actions)"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git commit --all --message "🪖 Update the Helm repository"
          git push
...
