---
# Default values for Storage: NFS.

# --- | NFS configuration
nfs:
  server: 127.0.0.1
  path: /
  capacity: 10Gi

# --- | Metadata values

# This is to override the chart name.
nameOverride: ''
# Specify extra annotations.
annotations: {}
# Specify extra labels.
labels: {}
...
