---
# --- | Default values for NFS
nfs:
  server: 127.0.0.1
  path: /
  capacity: 10Gi

persistenVolume:
  enabled: true

# --- | Overriding 'template' chart values
metadata:
  # Additional component label
  labels:
    app.kubernetes.io/component: "storage"
